import buildsMetadata from "@/content/builds-metadata.json";

/**
 * `/builds` cards (deck 17.5, verbatim).
 *
 * Card grammar per the deck: status chip, name, what it is in two sentences
 * at most, one mono PROVES line. No gated numeral appears on any card; the
 * section's one gated value is the headline, which resolves through
 * `buildsHeadline` in `content/proof-metrics.ts` (bank A7).
 *
 * Eras come from `content/builds-metadata.json`, regenerated by
 * `scripts/builds-metadata.mjs` from repo metadata (git history where a
 * repository exists locally, a recorded window with a named source where one
 * does not). Employer and product naming per story bank A6.
 *
 * Links point only at artifacts a reader can open today: the three public
 * GitHub repositories, verified 2026-08-06. jobos and the analytics platform
 * are private repositories and the employer systems are internal, so those
 * cards carry no link; their PROVES line names the constraint instead.
 */

export type BuildStatus = "operating" | "shipped" | "open-source" | "you-are-here";

export const buildStatusChips: Record<BuildStatus, string> = {
  operating: "Operating",
  shipped: "Shipped",
  "open-source": "Open source",
  "you-are-here": "You are here",
};

export type BuildCard = {
  /** Key into `builds-metadata.json`. */
  id: string;
  name: string;
  status: BuildStatus;
  /** Deck 17.5 body, verbatim. Two sentences maximum. */
  body: string;
  /** Deck 17.5 PROVES line, verbatim, without the prefix. */
  proves: string;
  /** Public artifact, when one exists. */
  href?: string;
  hrefLabel?: string;
};

export const buildCards: BuildCard[] = [
  {
    id: "jobos",
    name: "jobos",
    status: "operating",
    body: "A job-search operating system: pipeline CRM, application packet factory, scoring, and a daily driver. Built to run my own search; it staged the application that may have brought you here.",
    proves: "Builds tools he operates daily.",
  },
  {
    id: "tsi-marketing-machine",
    name: "TSI marketing machine",
    status: "operating",
    body: "AI orchestration over TSI's CRM and marketing stack: proposal triage, research, competitive intelligence, content, and executive reporting. Agents stage the work, humans approve it, and every run leaves an audit trail.",
    proves: "Governed AI in production at a PE-backed enterprise.",
  },
  {
    id: "tsi-marketing-analytics",
    name: "TSI marketing analytics",
    status: "operating",
    body: "The analytics platform behind TSI's marketing decisions: attribution, funnel inspection, and the reporting leadership runs the week from.",
    proves: "The instrumentation half of the pipeline-truth chapter, as software.",
  },
  {
    id: "tsi-video-studio",
    name: "TSI video studio",
    status: "shipped",
    body: "A programmatic video pipeline that turns briefs into branded motion assets.",
    proves: "Creative production treated as a system.",
  },
  {
    id: "tsi-interactive-tools",
    name: "TSI interactive tools",
    status: "shipped",
    body: "ROI calculator, risk grader, and benchmark explorer, shipped as tools sales brings into deals.",
    proves: "Marketing that ships product, not collateral.",
  },
  {
    id: "debtnext-rebuild",
    name: "DebtNext.com rebuild",
    status: "shipped",
    body: "A production rebuild of DebtNext.com in Next.js and Tailwind. Public repository.",
    proves: "Taste under production constraints, in the open.",
    href: "https://github.com/connorsewer/debtnext-com-redesign",
    hrefLabel: "Repository",
  },
  {
    id: "mcos",
    name: "mcOS",
    status: "open-source",
    body: "A mission-control dashboard for running multi-agent squads. Open source.",
    proves: "Agent direction as a practice, before it was a job title.",
    href: "https://github.com/connorsewer/mcOS",
    hrefLabel: "Repository",
  },
  {
    id: "hermes-agent",
    name: "hermes-agent",
    status: "open-source",
    body: "An experiment in personal AI that accumulates context and grows with its operator. Open source.",
    proves: "Curiosity with a commit history.",
  },
  {
    id: "this-site",
    name: "This site",
    status: "you-are-here",
    body: "The manual you are reading: a claim gate every number resolves through, a voice scanner, build-time word counts, and an x-ray mode that annotates the page.",
    proves: "The page is the demo.",
    href: "https://github.com/connorsewer/connorlaughl.in",
    hrefLabel: "Repository",
  },
];

/** Era string for a card, from the committed metadata record. */
export function buildEra(id: string): string {
  const entry = (buildsMetadata.builds as Record<string, { era: string }>)[id];
  return entry?.era ?? "2026";
}
